Deny same ip kills
RoboMWM/SimpleClans pull request #5
Opened 2018-05-03 23:07 UTC by ArtNRG

Cancel killing calculating if the attacker and the victim have the same IP address. 
The check can be turned on or off using config.yml.

2018-05-04 01:30 UTC, RoboMWM commented
Oh, took me a while to realize you PR'd to my repo, not the parent repo. 

Anyways, it looks okay, but should default off to maintain original behavior (e.g. I don't have an issue with alt accounts.)

While you're at it you might want to fix the indentation on that if statement.

2018-05-04 06:54 UTC, ArtNRG commented
That was my first PR and I accidentally mixed up the branches and repos.
I already sent another one to the correct repo.

2019-03-01 00:28 UTC, RoboMWM requested changes

2019-03-01 00:28 UTC, RoboMWM commented on src/main/java/net/sacredlabyrinth/phaed/simpleclans/listeners/SCEntityListener.java
> +            		if (attacker.getAddress().getHostString().equals(victim.getAddress().getHostString()))
This can be moved up into the second if-statement with an `&&` to avoid unnecessary nesting.

2019-08-10 20:40 UTC, RoboMWM commented
Closing for two reasons:

Primary reason is because I want it out of my search results for open issues in this org : p

Secondary reason is this excludes multiple legitimate players from the same place. Perhaps a system similar to GP's could be used for identifying alt accounts.

Thirdly, I'm trying to not maintain this repo anymore as my PRs to upstream are now getting in (with some poking).

2019-08-10 20:40 UTC, closed without merging